name: ci
on:
  pull_request:
  release:
    types: [published]
  push:
    branches:
      - master

jobs:
  Test:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - windows-2022
        compiler:
          - clang

        include:
          - os: windows-2022
            compiler: msvc

    steps:
      - uses: actions/checkout@v3

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows' )}}
          cmake: true
          ninja: true
          vcpkg: true

      - name: Configure
        run: cmake "--preset=$("${{ matrix.os }}".split("-")[0])-${{ matrix.compiler }}-debug"

      - name: Build
        run: cmake --build "--preset=$("${{ matrix.os }}".split("-")[0])-${{ matrix.compiler }}-debug"