name: Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      
      matrix:
        os: [ubuntu-latest, windows-2022]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Cpp
      uses: aminya/setup-cpp@v1
      with:
          vcvarsall: ${{ contains(matrix.os, 'windows' )}}
          cmake: false
          ninja: true
          vcpkg: false


    - name: Configure
      shell: pwsh
      run: cmake --preset=x64-debug

    - name: Build
      run: cmake --build --preset=x64-debug
