name: ci

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os:
          - ubuntu-22.04
          - windows-2022
        compiler:
          - llvm
        build_type:
          - debug
          - release
        include:
          - os: windows-2022
          - compiler: msvc

    steps:
    - uses: actions/checkout@v3

    - name: Setup Cpp
      uses: aminya/setup-cpp@v1
      with:
          vcvarsall: ${{ contains(matrix.os, 'windows' )}}
          cmake: true
          ninja: true
          vcpkg: true

    - name: Configure
      run: cmake --preset=$("${{matrix.os}}".split("-")[0])-${{matrix.compiler}}-${{matrix.build_type}}

    - name: Build
      run: cmake --build --preset=x64-debug
