name: ci

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.compiler }} ${{ matrix.build_type }}
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - windows-2022
        compiler:
          - llvm
        build_type:
          - Debug
          - Release

        include:
          - os: windows-2022
            compiler: msvc
            build_type: Debug
          - os: windows-2022
            compiler: msvc
            build_type: Release

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Cpp Environment
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows') }}
          cmake: true
          ninja: true
          vcpkg: true

      - name: Install SFML Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -qq
          sudo apt-get install libudev-dev libx11-dev libxrandr-dev libxcursor-dev libxi-dev libgl1-mesa-dev -y -q

      - name: CMake Configure
        env:
          VCPKG_ROOT: '~/vcpkg'
        run: cmake --preset=${{ runner.os }}-${{ matrix.compiler }}-${{ matrix.build_type }}

      - name: CMake Build
        run: cmake --build --preset=${{ runner.os }}-${{ matrix.compiler }}-${{ matrix.build_type }}

  format:
    name: Formatting
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 15CF4D18AF4F7421
          sudo add-apt-repository 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main' -y
          sudo apt-get update -qq
          sudo apt-get install clang-format-16 colordiff -y -q

      - name: Format Code
        run: cmake -DCLANG_FORMAT_EXECUTABLE=clang-format-16 -P cmake/Format.cmake

      - name: Check Formatting
        run: |
          git diff --color=always | colordiff
          git diff --quiet --exit-code


